adaboostclassifier:
  algorithm: SAMME
  estimator: null
  learning_rate: 0.4
  n_estimators: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - i4
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    BAEAAA==
  random_state: 42
extratreesclassifier:
  bootstrap: true
  ccp_alpha: 0.0
  class_weight: {}
  criterion: gini
  max_depth: 11
  max_features: 1.0
  max_leaf_nodes: null
  max_samples: null
  min_impurity_decrease: 0.0002
  min_samples_leaf: 3
  min_samples_split: 2
  min_weight_fraction_leaf: 0.0
  monotonic_cst: null
  n_estimators: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    oAAAAA==
  n_jobs: -1
  oob_score: false
  random_state: 42
  verbose: 0
  warm_start: false
gaussiannb:
  priors: null
  var_smoothing: 1
gradientboostingclassifier:
  ccp_alpha: 0.0
  criterion: friedman_mse
  init: null
  learning_rate: 0.15
  loss: log_loss
  max_depth: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AgAAAA==
  max_features: log2
  max_leaf_nodes: null
  min_impurity_decrease: 0.5
  min_samples_leaf: 5
  min_samples_split: 7
  min_weight_fraction_leaf: 0.0
  n_estimators: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    qgAAAA==
  n_iter_no_change: null
  random_state: 42
  subsample: 0.7
  tol: 0.0001
  validation_fraction: 0.1
  verbose: 0
  warm_start: false
lgbmclassifier:
  bagging_fraction: 0.6
  bagging_freq: 5
  boosting_type: gbdt
  class_weight: null
  colsample_bytree: 1.0
  feature_fraction: 1.0
  importance_type: split
  learning_rate: 0.1
  max_depth: -1
  min_child_samples: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    RwAAAA==
  min_child_weight: 0.001
  min_split_gain: 0.6
  n_estimators: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    ggAAAA==
  n_jobs: -1
  num_leaves: 4
  objective: null
  random_state: 42
  reg_alpha: 0.3
  reg_lambda: 4
  subsample: 1.0
  subsample_for_bin: 200000
  subsample_freq: 0
lineardiscriminantanalysis:
  covariance_estimator: null
  n_components: null
  priors: null
  shrinkage: 0.1
  solver: lsqr
  store_covariance: false
  tol: 0.0001
logisticregression:
  C: 0.431
  class_weight: balanced
  dual: false
  fit_intercept: true
  intercept_scaling: 1
  l1_ratio: null
  max_iter: 1000
  multi_class: auto
  n_jobs: null
  penalty: l2
  random_state: 42
  solver: lbfgs
  tol: 0.0001
  verbose: 0
  warm_start: false
quadraticdiscriminantanalysis:
  priors: null
  reg_param: 0.87
  store_covariance: false
  tol: 0.0001
randomforestclassifier:
  bootstrap: true
  ccp_alpha: 0.0
  class_weight: {}
  criterion: entropy
  max_depth: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    CQAAAA==
  max_features: sqrt
  max_leaf_nodes: null
  max_samples: null
  min_impurity_decrease: 0
  min_samples_leaf: 6
  min_samples_split: 10
  min_weight_fraction_leaf: 0.0
  monotonic_cst: null
  n_estimators: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    5gAAAA==
  n_jobs: -1
  oob_score: false
  random_state: 42
  verbose: 0
  warm_start: false
ridgeclassifier:
  alpha: 1.0
  class_weight: null
  copy_X: true
  fit_intercept: true
  max_iter: null
  positive: false
  random_state: 42
  solver: auto
  tol: 0.0001
